Now that the custom assembly class loader initialization bug is fixed, it is no longer necessary to call Class.forName() in LoadTypeWrapper. Also fixed exception handling to wrap non-java.lang.Error exceptions in NoClassDefFoundError.